### ISSUE TITLE
Question about loading the dataset

### ISSUE THREAD

**Issue by jc-ryan** [jwkirchenbauer/lm-watermarking#7]
Hello,

I have been trying to load the dataset using Huggingface's datasets library, but have run into an issue with a "FileNotFoundError" message like this 
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/resolver.py", line 38, in resolve
    flags=socket.AI_ADDRCONFIG,
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 792, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/fsspec/implementations/http.py", line 396, in _info
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/fsspec/implementations/http.py", line 768, in _file_info
    r = await session.get(url, allow_redirects=ar, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/client.py", line 536, in _request
    req, traces=traces, timeout=real_timeout
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/conda/lib/python3.7/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host huggingface.co:443 ssl:default [Temporary failure in name resolution]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/watermarking/lm-watermarking/pilot.py", line 12, in <module>
    next(ds_iterator)
  File "/opt/conda/lib/python3.7/site-packages/datasets/iterable_dataset.py", line 937, in __iter__
    for key, example in ex_iterable:
  File "/opt/conda/lib/python3.7/site-packages/datasets/iterable_dataset.py", line 113, in __iter__
    yield from self.generate_examples_fn(**self.kwargs)
  File "/root/.cache/huggingface/modules/datasets_modules/datasets/c4/df532b158939272d032cc63ef19cd5b83e9b4d00c922b833e4cb18b2e9869b01/c4.py", line 88, in _generate_examples
    with gzip.open(open(filepath, "rb"), "rt", encoding="utf-8") as f:
  File "/opt/conda/lib/python3.7/site-packages/datasets/streaming.py", line 70, in wrapper
    return function(*args, use_auth_token=use_auth_token, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/datasets/download/streaming_download_manager.py", line 495, in xopen
    file_obj = fsspec.open(file, mode=mode, *args, **kwargs).open()
  File "/opt/conda/lib/python3.7/site-packages/fsspec/core.py", line 141, in open
    out = self.__enter__()
  File "/opt/conda/lib/python3.7/site-packages/fsspec/core.py", line 104, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/opt/conda/lib/python3.7/site-packages/fsspec/spec.py", line 1043, in open
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/fsspec/implementations/http.py", line 340, in _open
    size = size or self.info(path, **kwargs)["size"]
  File "/opt/conda/lib/python3.7/site-packages/fsspec/asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/fsspec/asyn.py", line 66, in sync
    raise return_result
  File "/opt/conda/lib/python3.7/site-packages/fsspec/asyn.py", line 26, in _runner
    result[0] = await coro
  File "/opt/conda/lib/python3.7/site-packages/fsspec/implementations/http.py", line 404, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://huggingface.co/datasets/allenai/c4/resolve/1ddc917116b730e1859edef32896ec5c16be51d0/realnewslike/c4-train.00000-of-00512.json.gz`.
I have tried to troubleshoot the issue by upgrading to the latest version of the datasets library, but the problem persists. However, I found that I can download the dataset directly from the link provided without any issues.

I was wondering if you have encountered this issue before and if you might have any suggestions on how to resolve it.

Thank you for your time and help!

**Comment by jwkirchenbauer** [comment]
So this seems like a [`datasets`](https://huggingface.co/docs/datasets) library question rather than a question concerning this repo or workflow. In particular, you're trying to load C4, one of the popular datasets available on huggingface, but one which is a "larger than disk" dataset and needs to be streamed. I would check that you have no issues loading smaller datasets with `streaming=False` and then I would maybe open an issue in the datasets repo with a minimum working example (say the top lines of your `pilot.py`) script to allow one of the maintainers to verify that this dataset isn't working correctly in streaming mode.
